import { DecisionAnalysis } from '../types/decision';

export function generateMarkdownReport(decision: DecisionAnalysis): string {
  const { title, context, verdict, options, comparisonMatrix, scenarioHistory } = decision;

  let md = `# The Tiebreaker Decision Intelligence Report\n\n`;
  md += `**Decision Question:** ${title}\n`;
  if (context) md += `**Context:** ${context}\n`;
  md += `**Analysis Date:** ${new Date(decision.createdAt).toLocaleDateString()}\n\n`;
  md += `---\n\n`;

  md += `## 🏆 The Tiebreaker Recommendation\n\n`;
  md += `### Winner: **${verdict.winnerTitle}** (Confidence: ${verdict.confidencePercent}%)\n\n`;
  md += `> **The Decisive Factor:** ${verdict.theDecisiveFactor}\n\n`;
  md += `- **The Hard Truth:** ${verdict.hardTruth}\n`;
  md += `- **12-Month Pre-Mortem:** ${verdict.preMortem}\n`;
  md += `- **Contingency Safety Hedge:** ${verdict.contingencyPlan}\n`;
  md += `- **Decision Reversibility:** ${verdict.reversibleDoorAnalysis?.type} — ${verdict.reversibleDoorAnalysis?.reasoning}\n\n`;

  if (verdict.actionPlan30Days && verdict.actionPlan30Days.length > 0) {
    md += `### 30-Day Execution Plan\n`;
    verdict.actionPlan30Days.forEach((step, i) => {
      md += `${i + 1}. ${step}\n`;
    });
    md += `\n`;
  }

  md += `---\n\n`;
  md += `## ⚖️ Options Analysis (Pros & Cons)\n\n`;
  options.forEach((opt, idx) => {
    md += `### Option ${String.fromCharCode(65 + idx)}: ${opt.title}\n`;
    md += `*${opt.tagline}*\n\n`;

    md += `#### Pros\n`;
    opt.pros.forEach((p) => {
      md += `- **${p.text}** (Impact: ${p.weight}/5, ${p.category})\n  ${p.detail}\n`;
      if (p.counterpoint) md += `  *Nuance:* ${p.counterpoint}\n`;
    });
    md += `\n`;

    md += `#### Cons\n`;
    opt.cons.forEach((c) => {
      md += `- **${c.text}** (Severity: ${c.weight}/5, ${c.category})\n  ${c.detail}\n`;
      if (c.mitigation) md += `  *Mitigation:* ${c.mitigation}\n`;
    });
    md += `\n`;
  });

  md += `---\n\n`;
  md += `## 📊 Multi-Criteria Matrix\n\n`;
  md += `| Evaluation Criteria | Weight | ${options.map((o) => o.title).join(' | ')} |\n`;
  md += `| :--- | :---: | ${options.map(() => ':---:').join(' | ')} |\n`;
  comparisonMatrix.forEach((row) => {
    const scores = options.map((opt) => {
      const cell = row.optionScores[opt.id];
      return cell ? `${cell.score}/10` : '5/10';
    });
    md += `| **${row.name}** | ${row.weight}x | ${scores.join(' | ')} |\n`;
  });
  md += `\n`;

  md += `---\n\n`;
  md += `## 🧭 SWOT Analysis Matrix\n\n`;
  options.forEach((opt) => {
    md += `### ${opt.title} — SWOT\n`;
    md += `- **Strengths:** ${opt.swot?.strengths.join(', ') || 'N/A'}\n`;
    md += `- **Weaknesses:** ${opt.swot?.weaknesses.join(', ') || 'N/A'}\n`;
    md += `- **Opportunities:** ${opt.swot?.opportunities.join(', ') || 'N/A'}\n`;
    md += `- **Threats:** ${opt.swot?.threats.join(', ') || 'N/A'}\n\n`;
  });

  if (scenarioHistory && scenarioHistory.length > 0) {
    md += `---\n\n`;
    md += `## 🔮 "What-If" Scenarios Tested\n\n`;
    scenarioHistory.forEach((sc) => {
      md += `### Scenario: "${sc.scenario}"\n`;
      md += `- **Revised Winner:** ${sc.winnerTitle}\n`;
      md += `- **Calculus Shift:** ${sc.impactSummary}\n`;
      md += `- **Operational Advice:** ${sc.keyAdvice}\n\n`;
    });
  }

  md += `\n*Generated by The Tiebreaker — AI Decision Intelligence*\n`;

  return md;
}

export function downloadMarkdown(filename: string, content: string) {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
